### ISSUE TITLE
UnboundLocalError: local variable 'result' referenced before assignment

### ISSUE THREAD

**Issue by fluffy-critter** [bear/ronkyuu#19]
When running in Python 3.7:

```
Traceback (most recent call last):
  File "/Users/fluffy/.local/share/virtualenvs/Pushl-kcLf-ZN8/bin/pushl", line 11, in <module>
    load_entry_point('Pushl', 'console_scripts', 'pushl')()
  File "/Users/fluffy/projects/Pushl/pushl/__main__.py", line 68, in main
    entries.send_webmentions(entry, previous, [None])
  File "/Users/fluffy/projects/Pushl/pushl/entries.py", line 121, in send_webmentions
    ronkyuu.webmention.sendWebmention(entry.url, link)
  File "/Users/fluffy/.local/share/virtualenvs/Pushl-kcLf-ZN8/lib/python3.7/site-packages/ronkyuu/webmention.py", line 249, in sendWebmention
    return result
UnboundLocalError: local variable 'result' referenced before assignment
```

This is with ronkyuu 0.6 installed via pip.

**Comment by Lucas-C** [comment]
This is fixed by https://github.com/bear/ronkyuu/pull/25
